### ISSUE TITLE
Comma Separated Lists

### ISSUE THREAD

**Issue by candronikos** [SystemsBioinformatics/parcr#14]
I've tried parsing a single line of a CSV and I'm stumped! Note the headings in my case contain metadata that require their own parsers but for now, I'll be happy with a plain old CSV sample.

Could you provide an example of how this would work? 😊

**Comment by douwe** [comment]
Please bear in  mind that this is not an issue (error, unexpected behavior, etc.) with the package, but a question about how to use it.
As mentioned in the documentation and demonstrated in the examples, this parser is meant to be used to handle higher order structures, whereas structures like csv's or parsing of lines in general can be handled more efficiently with lower order functions like in this case strsplit(). As the examples show, you can combine the functions in this package with those lower order functions to build effective parsers.
